package havarnov:sandkasse;

interface runtime {
    variant request {
        eval(string),
    }

    variant error {
        message(string),
    }

    variant response {
        int(s32),
    }

    record register-params {
        name: string,
        is-int: bool,
    }

    resource ctx {
        constructor();
        handle: func(req: request) -> result<response, error>;
        register: func(req: register-params) -> result<bool, error>;
    }
}

world sandkasse {
    export runtime;
}
