package havarnoc:sandkasse;

world sandkasse {
    import registered-callback: func(payload: list<u8>) -> result<list<u8>, list<u8>>;
    export eval: func(payload: list<u8>) -> result<list<u8>, list<u8>>;
    export register: func(payload: list<u8>) -> result<list<u8>, list<u8>>;
}
