[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rquickjs = { version = "0.9.0" }
protocol = { path = "../protocol" }
rmp-serde = "1.3.0"
wit-bindgen = "0.41.0"
